README.md
notes and instructions added to clarify the steps required to get Superalgos running on a Pi (in headless mode with SSH)
=> Readme update for Raspberry Pi users

Projects/Superalgos/UI/Spaces/Docs-Space/ContextMenu.js
https://github.com/Superalgos/Superalgos/issues/664
=> Fix docs context menu in Firefox

Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/Announcements.js, Projects/Superalgos/UI/Function-Libraries/TradingSessionFunctions.js
Bug Fix for Telegram Announcements. This now ensures the JSON data received by the Announcement.js contains both the announcementFormula and announcementCondition (TradingSessionFunctions.js changes). Then the makeAnnoucement function has been changes to properly validate the announcementCondition and use the announcementFormula if valid.
(side note, this is my first Pull Request, sorry for any issues!)
=> Bug Fix: Telegram Announcement Formula and Condition Changes

Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js
- Adds password as a configuration option in the API key. This is required for some ccxt exchanges, like Coinbase Pro.
=> Add password to api key configuration

Projects/Superalgos/Schemas/AppSchema.json, Projects/Superalgos/Schemas/Docs-Nodes/exchange-account-key.json, Projects/Superalgos/Schemas/Docs-Topics/tested-exchanges-010-coinbasepro-test-status.json
- update docs to reference the password or passphrase setting required for Coinbase Pro.
=> update docs for coinbase pro api key password

Projects/Superalgos/Schemas/Docs-Reviews/superalgos-project-review-010-superalgos-review-complex-but-well-documented.json
I got an error when trying to submit this PR through the app so am doing it manually.  Hope that's ok.
=> My Superalgos Review

Projects/ProjectsSchema.json, Projects/Superalgos/Schemas/App-Schema/discord-bot.json, Projects/Superalgos/Schemas/App-Schema/social-bots.json, Projects/Superalgos/Schemas/Docs-Nodes/discord-bot.json, Projects/Superalgos/Schemas/Docs-Nodes/social-bots.json, Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Announcements/DiscordBot.js, Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Announcements/SocialBots.js, Projects/Superalgos/UI/Function-Libraries/ActionSwitch.js, Projects/Superalgos/UI/Function-Libraries/SocialBotsFunctions.js
webhook integration with Discord
=> WIP: Discord webhook announce

Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Announcements/DiscordBot.js, Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Announcements/SocialBots.js, Projects/Superalgos/UI/Function-Libraries/SocialBotsFunctions.js
`headers` vs `header` is the real magic in the request.
=> get discord announcements working

Docker/Dockerfile
- use `node setup` to install node dependencies
- use a python base image to support tensorflow
=> Update Dockerfile for latest code update dependencies

Docker/Dockerfile, README.md
As discused on Telegram with @ssplatt
=> Fix docker volumes

.github/workflows/docker.yml, Docker/Dockerfile, Docker/docker-compose.yml, README.md
- build amd64, arm64, and arm v7 containers
- update readme
- add more tags to give more options for pinning to specific branches or git tags (releases)
- `:latest` now points to the latest built container
- update docker-compose to pull from ghcr
=> Create docker containers for multiple architectures

Client/httpInterface.js, Projects/Superalgos/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-007-tutorial-step-what-about-free-riders.json, Projects/Superalgos/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-017-tutorial-step-breaking-up-the-command.json, Projects/Superalgos/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-021-tutorial-step-get-ready-to-push.json, Projects/Superalgos/Schemas/Docs-Tutorials/W/Welcome/Welcome-to-Superalgos/welcome-to-superalgos-082-tutorial-step-lets-take-a-peek..json, Projects/Superalgos/TS/Bot-Modules/API-Data-Fetcher-Bot/SingleMarketAPIDataFetcherBot.js, Projects/Superalgos/TS/Bot-Modules/Learning-Bot/Low-Frequency-Learning/LearningProcess.js, Projects/Superalgos/TS/Bot-Modules/Learning-Bot/SingleMarketLearningBot.js, Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/SingleMarketSensorBot.js, Projects/Superalgos/TS/Bot-Modules/Trading-Bot/SingleMarketTradingBot.js, Projects/Superalgos/TS/Task-Modules/DebugLog.js, Projects/Superalgos/TS/Task-Modules/FileStorage.js
Fixes some spelling mistakes I've noticed when doing the tutorials.
=> Plugins docs spelling fixes

Projects/Foundations/Plugins/Data-Mines/Quasar.json
Submission of an update of the Quasar data mine with finalization of the Volume agitation indicator in addition to On balance volume and volume oscillators for total, sell and buy volumes. Indicator bot and plotter are fully functional.
=> Contribution: This is my contribution to Superalgos

Projects/Foundations/Schemas/App-Schema/crypto-exchange.json, Projects/Foundations/Schemas/Docs-Nodes/C/Crypto/Crypto-Exchange/crypto-exchange.json, Projects/Foundations/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js
Please review and sorry for the formatting changes I'm not sure what you are using for formatting but I'm using prettier, let me know if that is an issue.
Thanks.
=> Added sandbox mode

Projects/Foundations/Schemas/Docs-Topics/B/Branches/Branches-Management-Messages/branches-management-messages-002-switching-branches-current-branch-changed.json, Projects/Foundations/Schemas/Docs-Topics/T/Troubleshooting/Troubleshooting/troubleshooting-017-problems-saving-the-workspace-or-plugins.json
=> Plugins docs

Client/httpInterface.js, Client/package-lock.json, Client/package.json, Docker/docker-compose.yml
- fixes #1270 
- adds package "lookpath" to check for command existence
- fixes environment variables in the docker-compose yml
=> Avoid crashing when attempting to use git command but it isn't available

Projects/Governance/Plugins/User-Profiles/teehanming.json
=> This is my first submission of User Profile teehanming

run.js
Minor spelling fix for the deprecated message text.
=> Spelling fix

Projects/Education/UI/Spaces/Tutorial-Space/TutorialSpace.js, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Logic/trading-logic-002-syntax-overview.json
=> Harden Tutorial Icon Loading

Projects/Foundations/Schemas/Docs-Nodes/W/Workspace/Workspace/workspace.json, Projects/Foundations/Schemas/Docs-Topics/H/How/How-to-Automate-Actions-at-The-Design-Space/how-to-automate-actions-at-the-design-space-009-automating-actions-testing-your-action.json
resolves #1715 
resolves #1177
=> reference debug topic in actions topic and typo fix

Projects/Foundations/Plugins/Data-Mines/quantum.json
My data mine containing keltner channel and MVWAP indicators
=> data quantum mine

Projects/Foundations/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/Snapshots.js, Projects/Foundations/TS/Task-Modules/FileStorage.js
Projects/Foundations/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/Snapshots.js
changes on this file:
adds only the first run a header to the to be saved content
next runs it fetches the CSV file
adds the new content to it
saves the file
this way you have a snapshot of all trades for referencing
Projects/Foundations/TS/Task-Modules/FileStorage.js
changes on this file:
-skips JSON validation (because it is no json file) and returns the text
=> Changes to CSV Snapshot and Filestorage foor CSV handling

Projects/Foundations/Plugins/Data-Mines/Sparta.json
=> Fix spelling of 'Strength'

Projects/Governance/Plugins/User-Profiles/elipwns.json
( I see I can't stuff in any other changes into a user-profile pull request, makes sense)
=> Added elipwns profile.

Projects/Education/UI/Spaces/Tutorial-Space/TutorialSpace.js
=> Add embedded Youtube videos to tutorial space

Projects/Foundations/Plugins/Workspaces/Tested-Exchanges.json, Projects/Foundations/Schemas/Docs-Topics/T/Tested/Tested-Exchanges/tested-exchanges-006-kucoin-test-status.json
Fetching candles ok
LIVE trading ok
=> Kucoin Tested

Docker/.dockerignore, Docker/Dockerfile, Docker/Dockerfile_old
Changed the base image to use Node official. 
Image size reduced, build time reduced.
=> Update Docker image

.dockerignore, Docker/Dockerfile, Launch-Scripts/launch-linux-mac.sh, Launch-Scripts/launch-windows.bat, platform.js
Add git to docker image
Consistency between docs and commands
=> Minor typos

Projects/Governance/Plugins/User-Profiles/ssplatt.json
=> Update ssplatt user profile

setup.js
avoid error messages in windows by checking if the directory exists before attempting to remove it
=> Check if directory exists before deleting

Projects/Governance/Plugins/User-Profiles/quantum8.json
Added governance claims section
=> User profile update

Projects/Governance/Plugins/User-Profiles/end-debug.json
=> This is my contribution to Superalgos

.dockerignore, Projects/Foundations/TS/Task-Modules/FileStorage.js
- fixes bug where path was trimming the M off "My-Data-Storage" and http files could not be found
=> Update file path trimming for fetch via http

console.html, electron-wrapper.js
Run with UI in background
Console logs
=> [Distribution] Update to packaged apps

.github/CODEOWNERS
slashes are not explicitly stated as being required but all of the examples on https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners show trailing slashes.
=> Add trailing slashes to the directory names in CODEOWNERS

.github/workflows/release_build.yml, .github/workflows/release_build_dev.yml, build/electron-builder.json
Linux amd64 and RaspberryPi
Update of automatic builds for Linux application
Simplification of release workflow
=> [Distribution] Addition of linux packaged application

Projects/Governance/Plugins/User-Profiles/9v5ij.json
=> User Profile 9v5ij

Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js
- set dict/hash if the dict/hash is defined
- set the okex brokerId if the brokerId is not already defined
=> update config options object parsing

.github/workflows/release_build_dev.yml
AKA get more sleep
Must be merged to master to be active
=> [Distribution] Typo

Projects/Foundations/UI/Spaces/CodeEditor-Space/CodeEditorSpace.js, Projects/Foundations/UI/Spaces/CodeEditor-Space/EditorPage.js
- side panel width
- trigger auto formatter for the code when opening the panel
=> code editor improvements

package-lock.json, package.json
- avoid major version updates since they tend to break things. stick to minor and patch version updates.
=> update a few dependency versions

Projects/Foundations/UI/Spaces/CodeEditor-Space/EditorPage.js
=> removed code completion for market/exchange objects 

Projects/Governance/Plugins/User-Profiles/DJ05GaZ.json
app.update user profile command would not work on my system and trying to rectify the issue.
=> Add user profile files via upload

Projects/Governance/Plugins/User-Profiles/quantum8.json
User profile updated to new claim style
=> User profile updated

Projects/Governance/Plugins/User-Profiles/NAmorim.json
=> User Profile: Claims

Projects/Foundations/Schemas/Docs-Books/first-steps-tutorials.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Languages/docs-languages-007-docs-in-turkish.json, Projects/Foundations/Schemas/Docs-Tutorials/W/Welcome/Welcome-to-Superalgos/welcome-to-superalgos-112-tutorial-step-get-in-touch.json, Projects/Foundations/Schemas/Docs-Tutorials/W/Welcome/Welcome-to-Superalgos/welcome-to-superalgos-116-tutorial-step-my-only-friend-the-end.json
Docs-languages-007-docs-in-turkish
Welcome-to-superalgos-112-tutorial-step-get-in-touch
welcome-to-superalgos-116-tutorial-step-my-only-friend-the-end
Docs-Books/first-steps-tutorials.json
=> Turkish translation pack

README.md
Fix https://github.com/Superalgos/Superalgos/issues/2748
=> Update Readme > M1 last needed step

Projects/Foundations/Schemas/Docs-Concepts/C/Community/Community/community.json, Projects/Foundations/Schemas/Docs-Concepts/U/User/User-Workspace/user-workspace.json, Projects/Foundations/Schemas/Docs-Nodes/T/Trading/Trading-Process-Instance/trading-process-instance.json, Projects/Foundations/Schemas/Docs-Nodes/W/Workspace/Workspace/workspace.json, Projects/Foundations/Schemas/Docs-Tutorials/W/Welcome/Welcome-to-Superalgos/welcome-to-superalgos-111-tutorial-step-help-us-with-a-star.json, Projects/TensorFlow/Schemas/Docs-Nodes/M/Machine/Machine-Learning/machine-learning.json
Docs-Concepts\C\Community\Community\community.json
Docs-Concepts\U\User\User-Workspace\user-workspace.json
Docs-Nodes\T\Trading\Trading-Process-Instance\trading-process-instance.json
Docs-Nodes\W\Workspace\Workspace\workspace.json
Docs-Nodes\M\Machine\Machine-Learning\machine-learning.json
=> New Pop-up Translation into Turkish

Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-002-tutorial-the-advanced-stuff.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-003-tutorial-step-you-are-in-command.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-004-tutorial-step-free-for-everyone.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-005-tutorial-step-a-brilliant-idea.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-006-tutorial-step-what-is-a-contribution.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-007-tutorial-step-what-about-free-riders.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-002-tutorial-the-advanced-stuff.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-003-tutorial-step-you-are-in-command.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-004-tutorial-step-free-for-everyone.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-005-tutorial-step-a-brilliant-idea.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-006-tutorial-step-what-is-a-contribution.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-007-tutorial-step-what-about-free-riders.json
=> Education-Translations (Turkish) (Beyond The Basics Tutorial)

Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Commands-Messages/docs-commands-messages-001-docs-message-saving-done.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-025-tutorial-step-set-up-the-token.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-026-tutorial-step-a-note-on-keys-and-tokens.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-028-tutorial-step-lets-run-the-command.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-029-tutorial-step-congrats-and-thank-you.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-030-tutorial-step-more-on-contributions.json, Projects/Foundations/Schemas/Docs-Tutorials/B/Beyond/Beyond-the-Basics/beyond-the-basics-031-tutorial-step-a-book-on-tutorials.json, Projects/Foundations/Schemas/Docs-Tutorials/W/Welcome/Welcome-to-Superalgos/welcome-to-superalgos-009-tutorial-step-repository-branches.json
Docs-Topics\D\Docs\Docs-Commands-Messages\docs-commands-messages-001-docs-message-saving-done.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-025-tutorial-step-set-up-the-token.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-026-tutorial-step-a-note-on-keys-and-tokens.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-028-tutorial-step-lets-run-the-command.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-029-tutorial-step-congrats-and-thank-you.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-030-tutorial-step-more-on-contributions.json
Docs-Tutorials\B\Beyond\Beyond-the-Basics\beyond-the-basics-031-tutorial-step-a-book-on-tutorials.json
=> Education-Translations (Turkish) (Beyond The Basics Tutorial) 

Projects/Governance/Schemas/Docs-Concepts/T/Token/Token-Power/token-power.json, Projects/Governance/Schemas/Docs-Nodes/C/Community/Community-Building-Programs/community-building-programs.json, Projects/Governance/Schemas/Docs-Nodes/R/Referral/Referral-Program/referral-program.json, Projects/Governance/Schemas/Docs-Nodes/T/Tokens/Tokens-Bonus/tokens-bonus.json
Docs-Concepts\T\Token\Token-Power\token-power.json
Docs-Nodes\C\Community\Community-Building-Programs\community-building-programs.json
Docs-Nodes\R\Referral\Referral-Program\referral-program.json
Docs-Nodes\T\Tokens\Tokens-Bonus\tokens-bonus.json
=> Education-Translations (Turkish) (Creating Your User Profile Tutorial)

Projects/Social-Bots/Schemas/App-Schema/discord-bot.json, Projects/Social-Bots/Schemas/Docs-Nodes/D/Discord/Discord-Bot/discord-bot.json
=> update discord bot documentation

Platform/PlatformApp.js, README.md, platform.js
The functionality to load workspaces at the CLI was undocumented, and misunderstood. I documented it, nothing more.
=> usage for loading workspaces at CLI

Docker/Dockerfile
- extra tf setup steps
- use node setup to get any updates that have been added to the script
=> update docker setup command to ensure it's getting all the latest updates

Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-001-testing-a-trading-idea-the-trigger-stage-tutorial.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-002-tutorial-testing-a-trading-idea.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-003-tutorial-step-the-pipeline.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-004-tutorial-step-do-you-have-the-data.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-005-tutorial-step-lets-mine-some-data..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-006-tutorial-step-lets-start-with-the-basics.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-007-tutorial-step-trading-systems.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-008-tutorial-step-right-out-of-the-box.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-009-tutorial-step-why-downtrends.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Testing/Testing-a-Trading-Idea-The-Trigger-Stage/testing-a-trading-idea-the-trigger-stage-010-tutorial-step-trigger-stage-events.json
Docs-Tutorials\T\Testing\Testi…\testing-a-trading-idea-the-trigger-stage-001-testing-a-trading-idea-the-trigger-stage-tutorial.json
Docs-Tutorials\T\Testing\Testing-a-Trading-Idea-The…\testing-a-trading-idea-the-trigger-stage-002-tutorial-testing-a-trading-idea.json
Docs-Tutorials\T\Testing\Testing-a-Trading-Idea-The-Trig…\testing-a-trading-idea-the-trigger-stage-003-tutorial-step-the-pipeline.json
Docs-Tutorials\T\Testing\Testing-a-Trading-Ide…\testing-a-trading-idea-the-trigger-stage-004-tutorial-step-do-you-have-the-data.json
Docs-Tutorials\T\Testing\Testing-a-Trading-Idea…\testing-a-trading-idea-the-trigger-stage-005-tutorial-step-lets-mine-some-data..json
Docs-Tutorials\T\Testing\Testing-a-Trading-…\testing-a-trading-idea-the-trigger-stage-006-tutorial-step-lets-start-with-the-basics. …
=> Education-Translations (Turkish)  Chapter VIII - Testing a Trading Idea - The Trigger Stage

Projects/Foundations/Schemas/Docs-Nodes/C/Charting/Charting-Space/charting-space.json, Projects/Foundations/Schemas/Docs-Nodes/S/Sensor/Sensor-Bot-Instance/sensor-bot-instance.json, Projects/Foundations/Schemas/Docs-Topics/C/Charting/Charting-Space/charting-space-005-layer-managers.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-001-trading-bot-layers-tutorial.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-002-tutorial-trading-bot-layers.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-003-tutorial-step-load-a-fresh-workspace.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-004-tutorial-step-freeze-dont-move.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-005-tutorial-step-ready-to-mine..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-006-tutorial-step-lets-mine-some-data..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-007-tutorial-step-are-we-up-to-date..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-008-tutorial-step-ready.-set.-go..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-009-tutorial-topic-trading-engine-layers.json, README.md
Projects\Foundations\Schemas\Docs-Tutorials\T\Trading\Trading-Bot-Layers\trading-bot-layers-001-trading-bot-layers-tutorial.json
Projects\Foundations\Schemas\Docs-Tutorials\T\Trading\Trading-Bot-Layers\trading-bot-layers-002-tutorial-trading-bot-layers.json
Projects\Foundations\Schemas\Docs-Tutorials\T\Trading\Trading-Bot-Layers\trading-bot-layers-003-tutorial-step-load-a-fresh-workspace.json
Projects\Foundations\Schemas\Docs-Tutorials\T\Trading\Trading-Bot-Layers\trading-bot-layers-004-tutorial-step-freeze-dont-move.json
Projects\Foundations\Schemas\Docs-Tutorials\T\Trading\Trading-Bot-Layers\trading-bot-layers-005-tutorial-step-ready-to-mine..json
Projects\Foundations\Schemas\Docs-Tutorials\T\Trading\Trading-Bot-Layers\trading-bot-layers-006-tutorial-step-lets-mine-some-data..json …
=> Education-Translations (Turkish) (Trading Bot Layers Tutorial)

Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-001-install-a-new-market-tutorial.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-002-tutorial-install-a-new-market.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-003-tutorial-topic-add-the-assets.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-004-tutorial-step-add-the-assets-1.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-005-tutorial-step-add-the-assets-2.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-006-tutorial-step-add-the-assets-3.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-007-tutorial-topic-set-up-the-market.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-008-tutorial-step-set-up-the-market-1.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-009-tutorial-step-set-up-the-market-2.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-010-tutorial-step-set-up-the-market-3.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-011-tutorial-step-set-up-the-market-4.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-012-tutorial-topic-install-the-market.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-013-tutorial-topic-network-verification.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-014-tutorial-step-network-verification-1.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-015-tutorial-step-network-verification-2.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-016-tutorial-step-network-verification-3.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-017-tutorial-step-network-verification-4.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-018-tutorial-topic-charts-verification.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-019-tutorial-step-charts-verification-1.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-020-tutorial-step-charts-verification-2.json, Projects/Foundations/Schemas/Docs-Tutorials/I/Install/Install-a-New-Market/install-a-new-market-021-tutorial-topic-you-made-it.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-001-install-a-new-market-tutorial.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-002-tutorial-install-a-new-market.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-003-tutorial-topic-add-the-assets.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-004-tutorial-step-add-the-assets-1.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-005-tutorial-step-add-the-assets-2.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-006-tutorial-step-add-the-assets-3.json
Docs-Tutorials\I\Install\Install-a-New-Market\install-a-new-market-007-tutorial-topic-set-up-the-market.json …
=> Education-Translations (Turkish) - Chapter X - Install a New Market

Projects/Governance/Schemas/Docs-Nodes/S/Signing/Signing-Account/signing-account.json, Projects/Governance/Schemas/Docs-Nodes/S/Social/Social-Trading-Bot-Reference/social-trading-bot-reference.json, Projects/Governance/Schemas/Docs-Nodes/T/Task/Task-Server-App-Reference/task-server-app-reference.json, Projects/Network/Schemas/Docs-Nodes/P/P2P/P2P-Network-Nodes/p2p-network-nodes.json, Projects/Network/Schemas/Docs-Topics/T/Trading/Trading-Signal-Overview/trading-signal-overview-011-trading-signal-integration-within-trading-bot-tasks.json, Projects/Network/Schemas/Docs-Topics/T/Trading/Trading-Signal-Overview/trading-signal-overview-012-connecting-to-a-network-node.json, Projects/Social-Trading/Schemas/Docs-Nodes/S/Social/Social-Trading-Bot/social-trading-bot.json, Projects/User-Apps/Schemas/Docs-Nodes/T/Task/Task-Server-App/task-server-app.json
Finished Overview
First set of node docs
=> Education - Docs - Next installment of Trading Signal docs

Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-034-tutorial-step-back-to-data-storage.json, Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-035-tutorial-step-another-timeline-chart.json, Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-036-tutorial-step-connection-two.json, Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-037-tutorial-step-don’t-forget-the-layers.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-034-tutorial-step-back-to-data-storage.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-035-tutorial-step-another-timeline-chart.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-036-tutorial-step-connection-two.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-037-tutorial-step-don’t-forget-the-layers.json
=> Education-Translations (Turkish) - Chapter XI - Setting Up a New Chart

Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-038-tutorial-step-check-the-chart.json, Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-039-tutorial-step-not-seeing-anything.json, Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-040-tutorial-step-easy-as-1-2-3.json, Projects/Foundations/Schemas/Docs-Tutorials/S/Setting/Setting-Up-a-New-Chart/setting-up-a-new-chart-041-tutorial-step-before-i-go.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-038-tutorial-step-check-the-chart.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-039-tutorial-step-not-seeing-anything.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-040-tutorial-step-easy-as-1-2-3.json
Docs-Tutorials\S\Setting\Setting-Up-a-New-Chart\setting-up-a-new-chart-041-tutorial-step-before-i-go.json
=> Education-Translations (Turkish) - Chapter XI - Setting Up a New Chart Finished

.gitmodules, Plugins/project-plugin-map.json
Example of adding a plugin, following instructions from Plugins/README.md
=> add Data-Mining plugin

setup.js
see upstream issue:
https://github.com/steveukx/git-js/issues/501
=> windows git-js checkout -B workaround

Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-013-tutorial-step-charting-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-014-tutorial-step-design-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-015-tutorial-step-floating-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-016-tutorial-step-side-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-017-tutorial-step-docs-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-018-tutorial-step-tutorial-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-019-tutorial-step-panel-space.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-020-tutorial-topic-files-component.json, Projects/Foundations/Schemas/Docs-Tutorials/D/Developers/Developers-Intro/developers-intro-021-tutorial-topic-parting-thoughts..json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-013-tutorial-step-charting-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-014-tutorial-step-design-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-015-tutorial-step-floating-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-016-tutorial-step-side-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-017-tutorial-step-docs-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-018-tutorial-step-tutorial-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-019-tutorial-step-panel-space.json
Docs-Tutorials\D\Developers\Developers-Intro\developers-intro-020-tutorial-topic-files-component.json …
=> Education-Translations (Turkish) - Chapter XIII Developers Intro Tutorial Finished

Projects/Foundations/Schemas/Docs-Topics/A/Alpha/Alpha-Data-Mine/alpha-data-mine-001-alpha-by-@rico4dev.json, Projects/Foundations/Schemas/Docs-Topics/A/Alpha/Alpha-Data-Mine/alpha-data-mine-002-average-true-range-atr-alpha-indicator.json, Projects/Foundations/Schemas/Docs-Topics/A/Alpha/Alpha-Data-Mine/alpha-data-mine-003-rate-of-change-roc-alpha-indicator.json, Projects/Foundations/Schemas/Docs-Topics/A/Alpha/Alpha-Data-Mine/alpha-data-mine-004-stochastic-alpha-indicator.json
Docs-Topics\A\Alpha\Alpha-Data-Mine\alpha-data-mine-001-alpha-by-@rico4dev.json
Docs-Topics\A\Alpha\Alpha-Data-Mine\alpha-data-mine-002-average-true-range-atr-alpha-indicator.json
Docs-Topics\A\Alpha\Alpha-Data-Mine\alpha-data-mine-003-rate-of-change-roc-alpha-indicator.json
Docs-Topics\A\Alpha\Alpha-Data-Mine\alpha-data-mine-004-stochastic-alpha-indicator.json
=> Education-Translations (Turkish) - Chapter I - Alpha Data Mine

Projects/Foundations/Schemas/Docs-Books/user-manual.json
Small change in german translation
=> Small change in german translation

Projects/Foundations/UI/Spaces/Floating-Space/CircularMenuItem.js, Projects/Foundations/UI/Spaces/Floating-Space/UiObject.js, Projects/Workspaces/UI/System-Action-Functions/UndoRedo.js
=> New uiObject method setQuickInfo (for left menu items)

Projects/Foundations/Schemas/Docs-Books/the-docs-explained.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-001-docs-intro.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-002-docs-page.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-003-docs-page-category.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-004-docs-page-number.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-005-docs-page-name.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-006-docs-topic-name.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-007-docs-tutorial-name.json, Projects/Foundations/Schemas/Docs-Topics/D/Docs/Docs-Basics/docs-basics-008-docs-paragraph.json
* Projects\Foundations\Schemas\Docs-Books\the-docs-explained.json
*.Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-001-docs-intro.json
* Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-002-docs-page.json
* Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-003-docs-page-category.json
* Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-004-docs-page-number.json
* Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-005-docs-page-name.json
* Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-006-docs-topic-name.json
* Projects\Foundations\Schemas\Docs-Topics\D\Docs\Docs-Basics\docs-basics-007-docs-tutorial-name.json
* …
=> Education-Translations (Turkish) (Docs Basics)

Projects/Data-Mining/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js
Reverts Superalgos/Superalgos#3901
Synhax error causes OHLCV fetching to crash. please correct and resubmit if necessary
=> Revert "Candlebatching Size"

Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-001-ts-lf-trading-bot-warning-calculating-actual-size-recalculated.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-002-ts-lf-trading-bot-warning-calculating-size-placed-recalculated.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-003-ts-lf-trading-bot-warning-simulating-actual-size-recalculated.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-004-ts-lf-trading-bot-warning-simulating-size-placed-recalculated.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-005-ts-lf-trading-bot-warning-simulating-slippage-subtracted.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-006-ts-lf-trading-bot-warning-simulating-slippage-added.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-007-ts-lf-trading-bot-warning-simulating-actual-rate-based-on-formula.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Warnings/ts-lf-trading-bot-warnings-008-ts-lf-trading-bot-warning-simulating-actual-rate-too-high.json
Projects\Foundations\Schemas\D…\ts-lf-trading-bot-warnings-001-ts-lf-trading-bot-warning-calculating-actual-size-recalculated.json
Projects\Foundations\Schemas\D…\ts-lf-trading-bot-warnings-002-ts-lf-trading-bot-warning-calculating-size-placed-recalculated.json
Projects\Foundations\Schemas\Do…\ts-lf-trading-bot-warnings-003-ts-lf-trading-bot-warning-simulating-actual-size-recalculated.json
Projects\Foundations\Schemas\D…\ts-lf-trading-bot-warnings-004-ts-lf-trading-bot-warning-simulating-size-placed-recalculated.json
Projects\Foundations\Schemas\Docs-…\ts-lf-trading-bot-warnings-005-ts-lf-trading-bot-warning-simulating-slippage-subtracted.json
Projects\Foundations\Schemas\Docs-Topic…\ts-lf-trading-bot-warnings-006-ts-lf-trading-bot-warning-simulating-slippage-added.json …
=> Education-Translations (Turkish) - TS LF Trading Bot Warnings

Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-005-ts-lf-trading-bot-error-maximum-balance-reached.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-006-ts-lf-trading-bot-error-minimum-balance-reached.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-011-ts-lf-trading-bot-error-target-rate-node-value-not-a-number.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-012-ts-lf-trading-bot-error-only-one-target-size-allowed.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-013-ts-lf-trading-bot-error-target-size-value-undefined.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-014-ts-lf-trading-bot-error-target-size-value-zero.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-015-ts-lf-trading-bot-error-order-reference-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-016-ts-lf-trading-bot-error-status-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-017-ts-lf-trading-bot-error-percentage-of-algorithm-size-property-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-018-ts-lf-trading-bot-error-serial-number-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-019-ts-lf-trading-bot-error-identifier-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-020-ts-lf-trading-bot-error-exchange-id-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-021-ts-lf-trading-bot-error-begin-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-022-ts-lf-trading-bot-error-end-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-023-ts-lf-trading-bot-error-rate-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-024-ts-lf-trading-bot-error-algorithm-name-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-025-ts-lf-trading-bot-error-order-counters-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-026-ts-lf-trading-bot-error-periods-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-027-ts-lf-trading-bot-error-order-statistics-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-028-ts-lf-trading-bot-error-days-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-029-ts-lf-trading-bot-error-percentage-filled-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-030-ts-lf-trading-bot-error-actual-rate-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-031-ts-lf-trading-bot-error-order-base-asset-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-032-ts-lf-trading-bot-error-size-node-missing.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-033-ts-lf-trading-bot-error-size-filled-node-missing.json
Projects\Foundations\Schemas\Docs-Topics\T\TS\TS-LF-Trading-Bot-Errors\ts-lf-trading-bot-errors-005-ts-lf-trading-bot-error-maximum-balance-reached.json
Projects\Foundations\Schemas\Docs-Topics\T\TS\TS-LF-Trading-Bot-Errors\ts-lf-trading-bot-errors-006-ts-lf-trading-bot-error-minimum-balance-reached.json
=> Education-Translations (Turkish) - TS LF Trading Bot Errors

Projects/Foundations/Schemas/Docs-Topics/S/Superalgos/Superalgos-Community-Task-Forces/superalgos-community-task-forces-001-community-task-forces.json, Projects/Foundations/Schemas/Docs-Topics/S/Superalgos/Superalgos-Community-Task-Forces/superalgos-community-task-forces-002-token-task-force.json, Projects/Foundations/Schemas/Docs-Topics/T/The/The-Art-of-Documenting/the-art-of-documenting-001-general-notions-on-documenting.json, Projects/Foundations/Schemas/Docs-Topics/T/The/The-Art-of-Documenting/the-art-of-documenting-002-documenting-new-projects.json, Projects/Foundations/Schemas/Docs-Topics/T/The/The-Art-of-Documenting/the-art-of-documenting-003-definition-pages.json, Projects/Foundations/Schemas/Docs-Topics/T/The/The-Art-of-Documenting/the-art-of-documenting-004-iterating-on-definitions.json, Projects/Foundations/Schemas/Docs-Topics/T/The/The-Art-of-Documenting/the-art-of-documenting-005-planning-topics-and-books.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Farms/trading-farms-001-trading-farms-fundamental-concepts.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Farms/trading-farms-002-trading-farms-set-up-a-network-of-nodes.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Farms/trading-farms-003-trading-farms-operating-a-trading-farm.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Logic/trading-logic-001-situations-conditions-and-formulas.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Logic/trading-logic-002-syntax-overview.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Logic/trading-logic-003-accessing-runtime-data.json, Projects/Foundations/Schemas/Docs-Topics/T/Trading/Trading-Logic/trading-logic-004-accessing-trading-system-definitions-and-session-parameters.json
Projects\Foundations\Schemas\Docs-Topics\T\Tradi…\trading-logic-001-situations-conditions-and-formulas.json
Projects\Foundations\Schemas\Docs-Topics\T\Trading\Trading-Logic\trading-logic-002-syntax-overview.json
Projects\Foundations\Schemas\Docs-Topics\T\Trading\Trading-…\trading-logic-003-accessing-runtime-data.json
Projects\Foundations\Sc…\trading-logic-004-accessing-trading-system-definitions-and-session-parameters.json
=> Education-Translations (Turkish) - Trading Logic

Projects/Foundations/Schemas/Docs-Nodes/C/Crypto/Crypto-Exchange/crypto-exchange.json, Projects/Foundations/Schemas/Docs-Nodes/L/Limit/Limit-Buy-Order/limit-buy-order.json, Projects/Foundations/Schemas/Docs-Nodes/L/Limit/Limit-Sell-Order/limit-sell-order.json, Projects/Foundations/Schemas/Docs-Nodes/M/Market/Market/market.json, Projects/Foundations/Schemas/Docs-Topics/T/Tested/Tested-Exchanges/tested-exchanges-007-kucoin-test-status.json
Docs documenting the use of new parameters to use for connecting with exchanges
=> Docs for new parameters

Projects/Foundations/Schemas/Docs-Nodes/C/Crypto/Crypto-Exchange/crypto-exchange.json
Ahah!! I finally managed to get rid of those 2 nasty jquery files!!!!
So now is ok, only fix typos in docs!
Merge it !!!!
=> Fix typos in docs

Projects/Algorithmic-Trading/Schemas/Docs-Nodes/T/Trading/Trading-Bot/trading-bot.json, Projects/Algorithmic-Trading/Schemas/Docs-Nodes/T/Trading/Trading-Mine/trading-mine.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-API-Maps/plugin-api-maps.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-Data-Mines/plugin-data-mines.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-File-Position/plugin-file-position.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-File/plugin-file.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-Super-Scripts/plugin-super-scripts.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-Trading-Engines/plugin-trading-engines.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-Trading-Mines/plugin-trading-mines.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-Trading-Systems/plugin-trading-systems.json, Projects/Community-Plugins/Schemas/Docs-Nodes/P/Plugin/Plugin-Tutorials/plugin-tutorials.json
Projects\Algorithmic-Trading\Schemas\Docs-Nodes\T\Trading\Trading-Bot\trading-bot.json
=> Education-Translations (Turkish) - Trading Bot

Projects/Data-Mining/Schemas/Docs-Nodes/A/API/API-Data-Fetcher-Bot/api-data-fetcher-bot.json, Projects/Data-Mining/Schemas/Docs-Nodes/D/Data/Data-Mine/data-mine.json, Projects/Data-Mining/Schemas/Docs-Nodes/I/Indicator/Indicator-Bot/indicator-bot.json, Projects/Data-Mining/Schemas/Docs-Nodes/S/Sensor/Sensor-Bot/sensor-bot.json, Projects/Education/Schemas/Docs-Nodes/D/Docs/Docs-Space-Settings/docs-space-settings.json, Projects/Education/Schemas/Docs-Nodes/D/Docs/Docs-Space-Style/docs-space-style.json, Projects/Education/Schemas/Docs-Nodes/T/Tutorial/Tutorial-Step/tutorial-step.json, Projects/Education/Schemas/Docs-Nodes/T/Tutorial/Tutorial-Topic/tutorial-topic.json, Projects/Education/Schemas/Docs-Nodes/T/Tutorial/Tutorial/tutorial.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Data-Fetcher-Bot-Instance/api-data-fetcher-bot-instance.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Data-Fetcher-Process-Instance/api-data-fetcher-process-instance.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Endpoint/api-endpoint.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Map/api-map.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Query-Response/api-query-response.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Query-Responses/api-query-responses.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Response-Field-Reference/api-response-field-reference.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Response-Field/api-response-field.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Response-Schema/api-response-schema.json, Projects/Foundations/Schemas/Docs-Nodes/A/API/API-Version/api-version.json, Projects/Foundations/Schemas/Docs-Nodes/A/APIs/APIs/apis.json, Projects/Foundations/Schemas/Docs-Nodes/A/Actual/Actual-Rate/actual-rate.json, Projects/Foundations/Schemas/Docs-Nodes/A/Actual/Actual-Size/actual-size.json, Projects/Foundations/Schemas/Docs-Nodes/A/Algorithm/Algorithm-Name/algorithm-name.json, Projects/Foundations/Schemas/Docs-Nodes/A/Amount/Amount-Received/amount-received.json, Projects/Foundations/Schemas/Docs-Nodes/A/Annualized/Annualized-Rate-Of-Return/annualized-rate-of-return.json
Projects\Data-Mining\Schemas\Docs-Nodes\A\API\API-Data-Fetcher-Bot\api-data-fetcher-bot.json
=> Education-Translations (Turkish) - API Data Fetcher Bot

Bitcoin-Factory/Round-5.md
Bitcoin-Factory Round 5 Indicators.
=> Round-5.md

Projects/Foundations/Schemas/Docs-Nodes/B/Back/Back-Learning-Session/back-learning-session.json, Projects/Foundations/Schemas/Docs-Nodes/B/Backtesting/Backtesting-Session/backtesting-session.json, Projects/Foundations/Schemas/Docs-Nodes/B/Balance/Balance/balance.json, Projects/Foundations/Schemas/Docs-Nodes/B/Begin/Begin-Balance/begin-balance.json, Projects/Foundations/Schemas/Docs-Nodes/B/Begin/Begin-Rate/begin-rate.json, Projects/Foundations/Schemas/Docs-Nodes/B/Begin/Begin/begin.json, Projects/Foundations/Schemas/Docs-Nodes/B/Bot/Bot-Data-Dependencies/bot-data-dependencies.json, Projects/Foundations/Schemas/Docs-Nodes/B/Bot/Bot-Layers/bot-layers.json, Projects/Foundations/Schemas/Docs-Nodes/B/Bot/Bot-Products/bot-products.json, Projects/Foundations/Schemas/Docs-Nodes/C/Calculations/Calculations-Procedure/calculations-procedure.json, Projects/Foundations/Schemas/Docs-Nodes/C/Cancel/Cancel-Order-Event/cancel-order-event.json, Projects/Foundations/Schemas/Docs-Nodes/C/Cancel/Cancel-Order/cancel-order.json, Projects/Foundations/Schemas/Docs-Nodes/C/Candle/Candle/candle.json, Projects/Foundations/Schemas/Docs-Nodes/C/Chart/Chart-Points/chart-points.json, Projects/Foundations/Schemas/Docs-Nodes/C/Close/Close-Execution/close-execution.json, Projects/Foundations/Schemas/Docs-Nodes/C/Close/Close-Order/close-order.json, Projects/Foundations/Schemas/Docs-Nodes/C/Close/Close-Position/close-position.json, Projects/Foundations/Schemas/Docs-Nodes/C/Close/Close-Stage-Event/close-stage-event.json, Projects/Foundations/Schemas/Docs-Nodes/C/Close/Close/close.json, Projects/Foundations/Schemas/Docs-Nodes/C/Condition/Condition/condition.json, Projects/Foundations/Schemas/Docs-Nodes/C/Create/Create-Order-Event/create-order-event.json, Projects/Foundations/Schemas/Docs-Nodes/C/Create/Create-Order/create-order.json, Projects/Foundations/Schemas/Docs-Nodes/C/Crypto/Crypto-Ecosystem/crypto-ecosystem.json, Projects/Foundations/Schemas/Docs-Nodes/C/Crypto/Crypto-Exchange/crypto-exchange.json, Projects/Foundations/Schemas/Docs-Nodes/C/Crypto/Crypto-Exchanges/crypto-exchanges.json, Projects/Foundations/Schemas/Docs-Nodes/C/Cycle/Cycle/cycle.json
Projects\Foundations\Schemas\Docs-Nodes\B\Back\Back-Learning-Session\back-learning-session.json
=> Education-Translations (Turkish) - Back Learning Session 

Bitcoin-Factory/README.md
Updated Bitcoin-Factory readme to reflect Raspbian OS current working status + basic required steps for install.
=> Updated Bitcoin-Factory Readme

Projects/Data-Mining/TS/Bot-Modules/Indicator-Bot/FromOneMinToMultiTimeFrameDaily.js, Projects/Foundations/TS/Function-Libraries/FromOneMinToMultiTimeFrameFunctions.js
The more major issues fixed where-  
Data.Range.json & Time.Frames.json where not being created, causing a issue with plotting.
"isString === true" Would not save strings as strings, Also causing a issue with plotting.
=> Fixes for API Data Saving

Projects/Foundations/Schemas/Docs-Topics/L/LF/LF-Trading-Bot-Available-Data-Structures/lf-trading-bot-available-data-structures-001-lf-trading-bot-chart-data-structure.json
Projects\Foundations\Schemas\Docs-Topics\L\LF\LF-Trading-Bot-Available-Data-Structures\lf-trading-bot-available-data-structures-001-lf-trading-bot-chart-data-structure.json
=> Education-Translations (Turkish) - LF Trading Bot - Chart Data Structure

Bitcoin-Factory/Test-Server/README.md, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/TestCasesManager.js
Fixed a bug in Bitcoin Factory Server's case generation.
Server README.md file has been edited.
=> Fixed a bug in Bitcoin Factory Server's case generation. 

Launch-Scripts/runUpdateGithubRepos.js
1. git safe.directory config is auto added
2. npm ci stage is removed.
=> git safe.directory config is auto added

Projects/Algorithmic-Trading/Schemas/Docs-Nodes/T/Trading/Trading-Bot/trading-bot.json, Projects/Foundations/Schemas/Docs-Nodes/P/Process/Process-Definition/process-definition.json
Trading bot update to specify stop/start running tasks after dependencies edit
=> Trading Bot Docs Updates

Projects/Data-Mining/TS/Bot-Modules/Indicator-Bot/FromOneMinToMultiTimeFrameMarket.js
Accidentally closed last PR for this file.
=> Add create Data.Range.json file and Time.Frames.json file

Bitcoin-Factory/Launch-Script/Ubuntu+/README.md, Bitcoin-Factory/Launch-Script/Ubuntu+/Ubuntu_SA_Installer.sh
This script should work on any Debian based OS. 
It is intended to be used as a convenience installation method (Particularly for new users trying to participate in the Bitcoin-Factory).
The user will be prompted to answer a few questions.
Then the script will handle everything from Cloning the users fork to building the docker image.
Once completed a restart is required for all changes to take effect.
=> Debian Based Superalgos Install Script

Bitcoin-Factory/Forecast-Client/README.md, Bitcoin-Factory/Forecast-Client/notebooks/Bitcoin_Factory_LSTM_Forecasting.ipynb, Bitcoin-Factory/Forecast-Client/notebooks/Bitcoin_Factory_LSTM_Forecasting.py, Bitcoin-Factory/Test-Client/README.md, Projects/Bitcoin-Factory/TS/Bot-Modules/Forecast-Client/ForecastClient.js
Fixed a few bugs that prevented the Forecast Client from working.
Added a README file for installing the Forecast Client.
=> Forecast Client  bugs are fixed

README.md
Gif showing how to fork all the branches.(Fix)
=> Update README.md (Gif fix)

Bitcoin-Factory/Forecast-Client/notebooks/Bitcoin_Factory_LSTM_Forecasting.py, Projects/Bitcoin-Factory/NT/Modules/ClientInterface.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Forecast-Client/ForecastClient.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/ForecastCasesManager.js, Projects/Network/NT/Modules/SocketInterfaces.js
- Enable parallel run of Forecast and Reforecast on Forecastclient
- Bugfix network node
=> Develop / Bugfix Bitcoin Factory Forecast

Platform/UI/Frame.js, Projects/Foundations/UI/Spaces/Charting-Space/ChartingSpace.js, Projects/Foundations/UI/Spaces/Charting-Space/EdgeEditor.js, Projects/Foundations/UI/Spaces/Charting-Space/Scales/RateScale.js, Projects/Foundations/UI/Spaces/Charting-Space/Scales/TimeFrameScale.js, Projects/Foundations/UI/Spaces/Charting-Space/Scales/TimeScale.js, Projects/Foundations/UI/Spaces/Charting-Space/TimeMachine.js, Projects/Foundations/UI/Spaces/Charting-Space/TimelineChart.js, Projects/Foundations/UI/Spaces/Panel-Space/Layer.js, Projects/Foundations/UI/Spaces/Panel-Space/LayersPanel.js, Projects/Foundations/UI/Utilities/DrawPrint.js
Completed fix to all changed files for situation where Space Style node is not connected to the Charting Space node.
=> Bug Fix for Charting Space Theme

Projects/Data-Mining/TS/Bot-Modules/API-Data-Fetcher-Bot/FetchingProcess.js
Fix for some of deep scans complaints.
=> Save Recursively Deepscan fix

.dockerignore
The container needs these files otherwise the UI won't load.
=> remove externalscripts from the dockerignore

Projects/Network/SA/Modules/P2PNetworkReachableNodes.js, Projects/Network/Schemas/Docs-Nodes/P/P2P/P2P-Network-Client/p2p-network-client.json, Projects/Network/Schemas/Docs-Nodes/P/P2P/P2P-Network-Node/p2p-network-node.json
Updated config location from previous PR along with the related docs.
Choosing a select network node to connect to is available at the P2P Network Client config located at each task.
=> Network Node Choice by Task

Bitcoin-Factory/ReadMeReinforcementLearning.md, Bitcoin-Factory/Test-Client/notebooks/Bitcoin_Factory_RL.py, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Client/TestClient.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/TestCasesManager.js
* new "Limit Orders" Feature in the Trading Environment
* new "Short Positions" Feature with "Market" and "Limit" Orders in the Trading Environment
* QuantStats Portfolio analytics (https://github.com/ranaroussi/quantstats)
=> Bitcoin Factory Reinforcement Learning Upgrade

Projects/Network/NT/Modules/SocketInterfaces.js, Projects/Network/NT/Modules/WebSocketsInterface.js, Projects/Network/SA/Modules/AppBootstrapingProcess.js, Projects/Network/SA/Modules/WebSocketsNetworkClient.js, Projects/Simulation/TS/Function-Libraries/SimulationFunctions.js, Projects/Trading-Signals/TS/Modules/IncomingCandleSignals.js
- Adjusting standard signal delay to 1 sec/user if < 60 users active
- Increasing timeout for signal receipt to 150 seconds
- Improving log verbosity for network node operators
Edit:
- Adding active bi-directional Websockets heartbeats to detect and handle hidden connection drops
=> P2P Network: Incremental improvements

Projects/Bitcoin-Factory/TS/Bot-Modules/Forecast-Client/ForecastClient.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Client/TestClient.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/ForecastCasesManager.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/TestCasesManager.js, Projects/Bitcoin-Factory/TS/Utilities/Miscellaneous.js
typo : Enlapsed -> Elapsed
typo : enlapsed -> elapsed
format date string "Elapsed time" : MM:SS -> HH:MM:SS
=> Projects/Bitcoin-Factory : typo

Bitcoin-Factory/Forecast-Client/notebooks/Bitcoin_Factory_RL.py, Bitcoin-Factory/Test-Client/notebooks/Bitcoin_Factory_RL.py, Dashboards/Client/websocketServer.js, Dashboards/UI/vueComponentsSource/App.vue, Dashboards/UI/vueComponentsSource/views/BitcoinFactoryView.vue, Platform/Client/bitcoinFactoryServer.js
make the prediction action variable human readable (0->Buy Long @ Market) and so on
=> Bitcoin Factory DashBoard polish

Projects/Foundations/Schemas/Docs-Topics/H/How/How-To/how-to-001-detach-and-attach-nodes.json
Projects\Foundations\Schemas\Docs-Topics\H\How\How-To\how-to-001-detach-and-attach-nodes.json
=> Translations (Turkish)

Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-001-hello-world-tutorial.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-002-tutorial-step-welcome.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-003-tutorial-step-look-around.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-004-tutorial-step-custom-data-mine.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-005-tutorial-step-the-strategy.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-006-tutorial-step-trading-system.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-007-tutorial-step-trigger-stage.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-008-tutorial-step-trigger-on.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-009-tutorial-step-trigger-off.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-010-tutorial-step-take-position.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-011-tutorial-step-open-stage.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-012-tutorial-step-manage-stage.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-013-tutorial-step-close-stage.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-014-tutorial-step-thats-it.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-015-tutorial-step-update-data-mines.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-016-tutorial-step-backtest.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-017-tutorial-step-final-step.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-018-tutorial-step-the-chart.json, Projects/Foundations/Schemas/Docs-Tutorials/H/Hello/Hello-World-Tutorial/hello-world-tutorial-019-tutorial-step-the-end.json
Completed translation on pages 001-019
=> Hello World Tutorials | Indonesian Translation

Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-001-creating-your-user-profile-tutorial.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-002-tutorial-step-better-together.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-003-tutorial-step-are-you-ready.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-004-tutorial-step-one-token-to-rule-them-all.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-005-tutorial-step-with-tokens-comes-responsibility.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-006-tutorial-step-a-mighty-meritocracy.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-007-tutorial-step-a-worthy-contribution.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-008-tutorial-step-what’s-in-a-profile.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-009-tutorial-step-program-participation.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-010-tutorial-step-where-it-all-begins.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-011-tutorial-step-profile-in-a-heartbeat.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-012-tutorial-step-pump-that-heartbeat.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-013-tutorial-step-oh-so-shiny.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-014-tutorial-step-only-you.json, Projects/Governance/Schemas/Docs-Tutorials/C/Creating/Creating-Your-User-Profile-Tutorial/creating-your-user-profile-tutorial-015-tutorial-step-under-the-hood.json
Updated regularly until 44 pages
=> Creating Your User Profile Tutorial 001-015 | Indonesian Translation

Bitcoin-Factory/Test-Server/README.md
In test server section, point 8 was added which details adding the P2P Network client node, references and adding further nodes.
=> Add the part for adding P2P network node client

Platform/Client/Http-Routes/gov.js, Platform/Client/web3Server.js, Projects/Governance/UI/Spaces/Reports-Space/CommandInterface.js
Fixing some logging issues, adding feature to manually include/exclude users from distribution for cases where the distribution may need to get restarted
=> Governance: Enhancements to distribution logic

Projects/Community-Plugins/SA/Utilities/PluginsAtGithub.js, Projects/Social-Trading/SA/Function-Libraries/PostsStorage.js, Projects/Social-Trading/SA/Function-Libraries/UserProfile.js, Social-Trading/SocialTradingApp.js
=> SocialTrading app to create pull request

Projects/Social-Trading/SA/Function-Libraries/UserProfile.js, Social-Trading/Client/expressHttpInterface/services/post.service.js, Social-Trading/Vue-UI/src/components/PostComponents/Post.vue, Social-Trading/Vue-UI/src/components/UploaderComponents/UploadImagePanel.vue, Social-Trading/Vue-UI/src/store/index.js, Social-Trading/Vue-UI/src/views/SocialTradingView.vue
Can upload images / add emoji's
New lines now work in posts.
Text input now expands with content
=>  Text input upgrades

Projects/Social-Trading/SA/Modules/SocialGraphNetworkServiceClient.js, Social-Trading/Client/expressHttpInterface/controllers/social.controller.js, Social-Trading/Client/expressHttpInterface/controllers/users.controller.js, Social-Trading/Client/expressHttpInterface/routes/index.js, Social-Trading/Client/expressHttpInterface/routes/social.routes.js, Social-Trading/Client/expressHttpInterface/routes/user.routes.js, Social-Trading/Client/expressHttpInterface/services/index.js, Social-Trading/Client/expressHttpInterface/services/social.service.js, Social-Trading/Client/expressHttpInterface/services/user.service.js, Social-Trading/Vue-UI/src/components/FollowComponents/FollowPanel.vue, Social-Trading/Vue-UI/src/components/PostComponents/NewPost.vue, Social-Trading/Vue-UI/src/services/ProfileService.js, Social-Trading/Vue-UI/src/services/SocialService.js, Social-Trading/Vue-UI/src/store/index.js
Setup start of query endpoints on the client side. 
Moved follow() endpoint to the new "social.service" (query endpoints).
Finished backend to return user profile data from GitHub Storage.
User profile data returns to UI and works!
=> Get User Profile Data Working!

Social-Trading/Vue-UI/src/components/FollowComponents/FollowPanel.vue, Social-Trading/Vue-UI/src/components/ProfileComponents/Profile.vue, Social-Trading/Vue-UI/src/components/ProfileComponents/ProfilePanel.vue, Social-Trading/Vue-UI/src/services/ProfileService.js, Social-Trading/Vue-UI/src/services/SocialService.js, Social-Trading/Vue-UI/src/store/index.js, Social-Trading/Vue-UI/src/views/SocialTradingView.vue
Can now update profile picture, name, and bio. The picture updates your profile picture throughout the UI and the name / bio display when viewing your profile.
=> Profile Component updates.

Social-Trading/Client/expressHttpInterface/services/post.service.js, Social-Trading/Vue-UI/src/components/PostComponents/Comment.vue, Social-Trading/Vue-UI/src/components/PostComponents/CommentInput.vue, Social-Trading/Vue-UI/src/components/PostComponents/CommentList.vue, Social-Trading/Vue-UI/src/components/PostComponents/Post.vue, Social-Trading/Vue-UI/src/components/PostComponents/PostComments.vue, Social-Trading/Vue-UI/src/components/PostComponents/PostList.vue, Social-Trading/Vue-UI/src/services/PostService.js, Social-Trading/Vue-UI/src/store/index.js, Social-Trading/Vue-UI/src/views/SocialTradingView.vue
Main feed displayed now filters to only display eventType 10 (posts),
Comment count now displays on each post.
Can click on comment to open comment post component - (start)
=> Add filter post feed + start post comments

Projects/Social-Trading/SA/Modules/SocialGraphNetworkServiceClient.js, Social-Trading/Client/expressHttpInterface/controllers/social.controller.js, Social-Trading/Client/expressHttpInterface/routes/social.routes.js, Social-Trading/Client/expressHttpInterface/services/social.service.js, Social-Trading/Client/expressHttpInterface/services/user.service.js, Social-Trading/Vue-UI/src/components/LogoutComponent.vue, Social-Trading/Vue-UI/src/components/PostComponents/Post.vue, Social-Trading/Vue-UI/src/components/ProfileComponents/ProfilePanel.vue, Social-Trading/Vue-UI/src/components/ProfileComponents/UsersProfilePanel.vue, Social-Trading/Vue-UI/src/components/UploaderComponents/UploadImagePanel.vue, Social-Trading/Vue-UI/src/services/ProfileService.js, Social-Trading/Vue-UI/src/services/SocialService.js, Social-Trading/Vue-UI/src/store/index.js, Social-Trading/Vue-UI/src/views/SocialTradingView.vue
When viewing a posts comments the posters profile username, picture, banner, and bio display at the top.
Can now set a banner picture when updating our profiles.
Setup logout component - basic setup in place. Still needs functionality.
=> Display Comment Posters Profile, Setup Logout Component & More

Bitcoin-Factory/Test-Client/notebooks/Bitcoin_Factory_LSTM.py
error_bad_lines and warn_bad_lines is depreciated. changed to 
on_bad_lines='error',
on_bad_line='warn'
=> Update to _LSTM.py removing depreciation

Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-001-trading-bot-layers-tutorial.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-002-tutorial-trading-bot-layers.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-003-tutorial-step-load-a-fresh-workspace.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-004-tutorial-step-freeze-dont-move.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-005-tutorial-step-ready-to-mine..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-006-tutorial-step-lets-mine-some-data..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-007-tutorial-step-are-we-up-to-date..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-008-tutorial-step-ready.-set.-go..json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-009-tutorial-topic-trading-engine-layers.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-010-tutorial-step-1-2-3-counting.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-012-tutorial-step-how-about-the-rest.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-013-tutorial-step-et-voilà.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-014-tutorial-step-compartmentalize-it.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-015-tutorial-step-elephant-what-elephant.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-016-tutorial-step-making-sense-of-objects.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-017-tutorial-step-what-about-the-position.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-018-tutorial-step-the-beauty-of-the-triangle.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-019-tutorial-step-why-3-position-layers.json, Projects/Foundations/Schemas/Docs-Tutorials/T/Trading/Trading-Bot-Layers/trading-bot-layers-020-tutorial-step-remember-flexibility.json
Trading Bot Layers Tutorial pages 001-020
=> Indonesian Translation

Bitcoin-Factory/Test-Client/notebooks/Bitcoin_Factory_LSTM.py
Reverts Superalgos/Superalgos#4671
=> Revert "Update to _LSTM.py removing depreciation"

Projects/Trading-Signals/TS/Modules/IncomingTradingSignals.js, Projects/Trading-Signals/TS/Modules/OutgoingTradingSignals.js, TaskServer/TaskServer.js
Maybe one of these will help find the current issue with the trading signals?
=> Additional logging added for trading signals.

Bitcoin-Factory/Test-Server/README.md
Addition to the Mining Space at step 5. adding the Bitcoin Factory data mine This is so the results will show in the test server chart space.
=> Mining Space step 5 add Bitcoin-Factory data mine

Bitcoin-Factory/Test-Server/GenerateServerConfig.js, Bitcoin-Factory/Test-Server/README.md, Bitcoin-Factory/Test-Server/TestServerConfig.json
Script + Test Server Config File + ReadMe updates for script
=> Script for manually regenerating the Test Server Config

Projects/Governance/UI/Spaces/User-Profile-Space/UserProfile.js
This change contains two improvements affecting the Governance workspace:
- User profiles now displayed in alphabetical order, so it's easier to find a user if needed
- Issue resolved which led to hangups when switching from other workspaces to the Governance workspace
=> Governance: Alphabetical sorting of users in Workspace / Workspace switch issue

Projects/Network/SA/Modules/AppBootstrapingProcess.js, Projects/Social-Trading/SA/Modules/SocialGraphNetworkServiceClient.js, Social-Trading/Client/expressHttpInterface/controllers/posts.controller.js, Social-Trading/Client/expressHttpInterface/routes/post.routes.js, Social-Trading/Client/expressHttpInterface/services/post.service.js, Social-Trading/Vue-UI/src/components/CommentComponents/Comment.vue, Social-Trading/Vue-UI/src/components/CommentComponents/CommentInput.vue, Social-Trading/Vue-UI/src/components/EmojiComponents/ReactionPicker.vue, Social-Trading/Vue-UI/src/components/MenuComponents/MainMenu.vue, Social-Trading/Vue-UI/src/components/PostComponents/PostButtonBar.vue, Social-Trading/Vue-UI/src/components/PostComponents/PostComments.vue, Social-Trading/Vue-UI/src/components/PostComponents/PostComponent.vue, Social-Trading/Vue-UI/src/components/PostComponents/PostList.vue, Social-Trading/Vue-UI/src/components/PostComponents/RePostComponent.vue, Social-Trading/Vue-UI/src/services/PostService.js, Social-Trading/Vue-UI/src/store/index.js, Social-Trading/Vue-UI/src/views/SocialTradingView.vue
This is a larger update tested with the commented out code inside of AppBootstrapingProcess.js uncommented. This was done to gain stability at the network node by only connecting to my "localhost" network node.
=> Social Trading App Reposts working + misc updates

Platform/Client/webSocketsInterface.js, Projects/Foundations/TS/Task-Modules/EventServerClient.js, Projects/Network/SA/Modules/P2PNetworkStart.js
Reverts Superalgos/Superalgos#4833
=> Revert "Event Server: Hardening Websockets Connections"

Platform/WebServer/css/menu.css, Platform/WebServer/index.html
=> updated workspace title z-index.

Environment.js, Network/NetwokProfileManagerApp.js, NetworkProfileManager.js, Profile-Scripts/common.js, Profile-Scripts/create/create.js, Profile-Scripts/describe/describe.js, Profile-Scripts/update/update.js, Projects/Foundations/TS/Globals/Persistence.js, Projects/Network/NT/Globals/Persistence.js, Projects/Network/NT/Globals/Stores/FileStore.js, Projects/Network/NT/Globals/Stores/MongoDbStore.js, Projects/Network/SA/Modules/AppBootstrapingProcess.js, Projects/Network/SA/Modules/ProfileManagerAppBootstrapingProcess.js, Projects/ProjectsSchema.json
Added persistence layer to the network app.
Refactored network bootstrapping process to extract pulling of user profiles into a non-blocking sub process which runs on the 10 min schedule and will not block network -> client communications.
Base implementation of storage uses file storage with template to introduce MongoDB as an alternative.
=> adding storage for user profile persistence

.tests/Projects/Network/NT/Modules/SocketInterfaces.test.js, Projects/Network/NT/Modules/SocketInterfaces.js, Projects/Network/NT/Modules/WebRTCInterface.js, Projects/Network/NT/Modules/WebSocketsInterface.js, Projects/Network/SA/Modules/SocketNetworkClients.js, Projects/Portfolio-Management/TS/Modules/PortfolioManagerEventsClient.js, Social-Trading/Clean-UI/UI/WebSocketsWebAppClient.js
refactored the code to remove the unnessary 'n' in the work onMessage, because it was really annoying me.
=> refactored typo onMenssage to onMessage

Reports/RnD/OrderFetcherFromSA/OrderFetcherFromSA/OrderFetcherFromSA.cpp, Reports/RnD/OrderFetcherFromSA/OrderFetcherFromSA/OrderFetcherFromSA.h
Local to Report directory and doesn't affect the rest of SA.
=> Couple of fixes and tweaks to OrderFetcherSA

Projects/Network/SA/Globals/Stores/FileStore.js
=> resolved bug saving user balances on windows

Projects/Social-Trading/NT/Modules/Storage.js
Now the network always checks the other network node's DataRange file
=> Fixed the syncronizeWithTheNetwork timing issue

README.md, package.json
Version update following merge of develop v1.5.0 into master
=> Updating develop minor version to 1.6.0

Platform/Client/eventServer.js
This PR addresses the occasional outages of Trend Soaring and The BEAST trading signals.
A likely reason why only these signals are affected, but never Base Soaring, is that both Trend and Beast listen to the same market data completion event.
This PR addresses a design issue within the Event Server. When multiple listeners are subscribed to the same event, in very rare cases, a "stopListening" event of one listener could lead to the deletion of the required event handler, while the second listener's subscription was in progress of getting re-established (race condition). This led to the second listener no longer receiving the subscribed events going forward. The PR now adds a temporary deletion protection which is in place while new subscriptions are getting established.
=> Event Server: Avoid unintended deletes of eventHandlers

Projects/Foundations/Schemas/Docs-Reviews/S/Superalgos/Superalgos-Project-Review/superalgos-project-review-059-superalgos-review-lets-do-this-thing.json
Trying to follow tutorial steps. Is this what I am supposed to do?
=> Tutorial review

Platform/WebServer/locales/index.js, Projects/Foundations/UI/Spaces/Floating-Space/CircularMenuItem.js
fixed bugs with loading translations when values are missing
=> fixed bugs with missing translations
