.dockerignore, Dockerfile, docker-compose.yml
A very basic dockerfile and docker-compose config to aid in running the system as a containerized service. Tested on an amd64 server and an odroid c2 arm64 server.  The default run command is set to `node run noBrowser`, and `minMemo` is configured in the docker-compose config as being an optional flag. If you are running on a beefier host, just remove the line from the docker-compose.yml or comment it out. The default ports are exposed and mapped to the same ports on the host. The data and log directories are configured as volume mounts from the local directory.
docker compose basics:
- build with `docker-compose build`
- run with `docker-compose up`, exit with `Ctrl+C`
- check the status of the service with `docker-compose ps`
- run as a daemon in the background with `docker-compose up …
=> add dockerfile and compose config

Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingStages.js, Projects/Superalgos/UI/Function-Libraries/TradingSessionFunctions.js, UI/AppPreLoader.js
This bug fix moves the lightingPath entries for Announcements down further so that they are after the Create Order and Cancel Order event (and therefore get correctly added to the Create Order and Cancel Order Event).
It also adds a entry for making an Announcement as we move into the Manage Stage (as there was none but you can create Announcements for the Manage Stage).
=> Bug Fix for Announcements + Browser Type / Version Check

Projects/Superalgos/Schemas/Docs-Tutorials/testing-a-trading-idea-the-trigger-stage-072-tutorial-step-take-position-event.json
In tutorial step 72 of "Testing a Trading Idea - The Trigger Stage" the trigger off had a typo. Instead of 'off' it was 'of'
_/hey, sorry Henning, unfortunately we can't merge changes directly on the master branch. Please submit again to the plugins-dos branch..._
@julian-molina sorry mate! I was not paying attention and selected your master branch by accident
=> Fixed a typo where 'of' was written instead of 'off'

.github/workflows/docker.yml, README.md
Issues addressed:
- Fix docker tagging: `latest` tag was not being added in GitHub Actions
- Add tagging for develop branch
- Remove duplicated namespace: container was being pushed to `ghcr.io/superalgos/superalgos/superalgos` instead of `ghcr.io/superalgos/superalgos`
- Update docker run instructions: Docker login is not necessary to pull the image
=> Docker tagging & cleanup

Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js
A bit of commentary on this one. 
There have been changes in CCXT behaviour that have changed how Superalgos processes the getOHLCVs function.
On March 10th the CCXT library was updated to latest version: 1.42.67 under https://github.com/Superalgos/Superalgos/commit/ac43839d5d127e53eba900b9e10483ad6091afe3.
NOTE: There have been subsequent updates since then, but this change introduced the changes in behaviour.
Prior to the CCXT library update the exchange.getOHLCVs command for CCXT would find the next valid "since" date and continue from this date if the provided since date was invalid (I.E. if you provided "1999-01-01" it would continue on from the first date in the market "2017-08-17").
After this library update CCXT provides OHLCV data for the limit as specified by the since date …
=> Bug Fixes for getOHLCVs from CCXT Library Update 

Projects/Foundations/TS/Task-Modules/package-lock.json, Projects/Foundations/TS/Task-Modules/package.json
I've been running this for over a week on Windows 10 and Ubuntu with no seen issues.
Reading the release notes there are no changes which should interfere with Superalgos.
=> Dependency: Change TaskServer WS from 7.4.0 to 7.4.6

Projects/Foundations/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js, Projects/Foundations/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/OrdersCalculations.js, Projects/Foundations/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/TradingOrders.js
Coinbase Pro removes the order from its records after it is closed so there is no way for Superalgos to get information about it, which returns an empty `order` object. From there we must assume none of the values within Superalgos have changed so no new order synchronization is necessary.
=> Sync trade calculations if the data is present

Brewfile, Docker/README.md, Docker/docker-compose.yml, README.md, package.json
- add table of contents to main readme
- clean up a few sections of the main readme
- move docker directions and info out to it's own readme
- add a Brewfile to quickly install requirements on Mac OS with Homebrew
- add a couple quick scripts to `package.json`
- the `package.json` can function similar to a `Makefile`
- `npm run setup` will execute `node setup noShortcuts`
- `npm start` will execute `node platform minMemo noBrowser` 
- change docker-compose to use `user` instead of trying to set uid/gid via env vars which didn't work to ensure file persistence works
=> Update READMEs, add brewfile, add npm script aliases

.github/workflows/docker.yml
effectively update the whitespace to move the 'release' to a different level.
=> update workflow to create a docker image off releases

package.json
- add `presetup` stage in the scripts section which will check out develop, pull the upstream (Superalgos/Superalgos) code in order to update the local fork
- add `postsetup` stage which will execute `npm start` which is an alias for `node platform minMemo noBrowser`
- with these, executing `npm run setup` will result in the code being refreshed, new node modules being installed, and then the platform started.
more info : https://docs.npmjs.com/cli/v7/using-npm/scripts
=> add special setup stages to package.json

Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js
use a static broker id for okex, overriding the default value provided by the CCXT library. This value can also be overriden in the workspace by adding a `"brokerId"` field to the API Key json.
=> set brokerid for okex

setup.js
currently, CI is broken due to a module error but the setup script does not exit with an error code so the builds continue as if there were no errors. This change should have the build fail when the script fails.
=> Add exit 1 when setup fails

Docker/Dockerfile, package.json
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies
> If a dependency can be used, but you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object. This is a map of package name to version or url, just like the dependencies object. The difference is that build failures do not cause installation to fail.
=> Optional-dependencies

Launch-Scripts/create-shortcut.js
- users should `npm ci` to install the packages which are defined in the package.json and package-lock.json
- use of `npm install` updates the local package-lock.json which we do not want normal users doing unintentionally
- when installing packages that are not necessary for the actual application, they should be installed globally (`-g`)
- other minor whitespace changes
=> install package to global scope to stop changing the package-lock.json

Projects/Foundations/UI/Spaces/Floating-Space/FloatingSpace.js
The condition `(displaceVector !== undefined)` in `Canvas.js` was always true, so that a grabbed node would always be dragged when using `Ctrl + ArrowKey`, even after the floating space container had been stopped at the canvas bounds by the physics function. It was easy to accidentally (or on purpose :/) drag nodes out of reach and visibility that way.
=> Fix dragging nodes out of bounds

Launch-Scripts/create-shortcut.js
This change fixes bug #3163, regarding hard coding `gnome-terminal` into the desktop launch command. I believe it is unnecessary to specify a terminal, and simply removed the explicit reference. Confirmed that this patch fixes the issue for my local Xubuntu install.
=> patch for desktop launcher bug GH #3163

Projects/Foundations/UI/Spaces/Floating-Space/UiObject.js, Projects/Foundations/UI/Spaces/Floating-Space/UiObjectConstructor.js, Projects/ProjectsSchema.json, Projects/Visual-Scripting/UI/Node-Action-Functions/NodeActionSwitch.js, Projects/Visual-Scripting/UI/Node-Action-Functions/ReferenceChildren.js
An on/off switch in the UI object menu to highlight referencing nodes and draw their reference lines. This is a corollary of the work done on undo/redo functionality.
=> New node action Highlight Referencing Nodes

setup.js
If user was on master, node setup explicitly changes them to develop branch of plugins.
=> always always checkout develop on setup

Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-001-ts-lf-trading-bot-error-evaluating-condition-error.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-002-ts-lf-trading-bot-error-evaluating-formula-error.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-003-ts-lf-trading-bot-error-formula-value-not-a-number.json, Projects/Foundations/Schemas/Docs-Topics/T/TS/TS-LF-Trading-Bot-Errors/ts-lf-trading-bot-errors-004-ts-lf-trading-bot-error-reference-to-phase-node-missing.json
Projects\Foundations\Schemas\Docs-Topics\T\TS\TS-LF-Trading-Bot-Errors\ts-lf-trading-bot-errors-001-ts-lf-trading-bot-error-evaluating-condition-error.json
Projects\Foundations\Schemas\Docs-Topics\T\TS\TS-LF-Trading-Bot-Errors\ts-lf-trading-bot-errors-002-ts-lf-trading-bot-error-evaluating-formula-error.json
Projects\Foundations\Schemas\Docs-Topics\T\TS\TS-LF-Trading-Bot-Errors\ts-lf-trading-bot-errors-003-ts-lf-trading-bot-error-formula-value-not-a-number.json
Projects\Foundations\Schemas\Docs-Topics\T\TS\TS-LF-Trading-Bot-Errors\ts-lf-trading-bot-errors-004-ts-lf-trading-bot-error-reference-to-phase-node-missing.json
=> Education-Translations (Turkish) - TS LF Trading Bot Errors

Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js, Projects/Algorithmic-Trading/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/OrdersCalculations.js, Projects/Data-Mining/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js
This PR involves 3 files:
1) HistoricOHLCVs.js -> sandBox + many more parameters we can now use when connecting to exchanges. Now we can use "options" as expected (it was not correctly implemented) and set limit, rateLimit ecc whitout the needing of using "API" that was supposed to be used for fetching candles in an alternative way.
2) ExchangeAPI.js -> sandBox is now correctly working and also all the above parameters are now included so to match the initial instantiation with the exchange. Inside this file the function createOrder is now able to accept parameters as per ccxt manual.
Added 2 more parameters that can be configured at the exchange node and at position node (ie for reduceOnly for example)
3) OrdersCalculation.js -> Initial changes to the code so now SA can correctly trade …
=> Fixes and Adds. Will write a comment on GitHub

Projects/Governance/Schemas/App-Schema/liquidity-program.json, Projects/Governance/Schemas/Docs-Nodes/L/Liquidity/Liquidity-Program/liquidity-program.json, Projects/Governance/Schemas/Docs-Nodes/L/Liquidity/Liquidity-Programs/liquidity-programs.json, Projects/Governance/UI/Function-Libraries/DistributionProcess.js, Projects/Governance/UI/Function-Libraries/LiquidityProgram.js, Projects/Governance/UI/Function-Libraries/TokenMining.js, Projects/Governance/UI/Spaces/Reports-Space/Liquidity.js, Projects/Governance/UI/Spaces/User-Profile-Space/UserProfile.js, Projects/Governance/UI/Utilities/Validations.js
Until now, we have summarized liquidity on asset basis to determine the share of rewards from one central asset pool (e.g. all SA/BTC liquidity across several exchanges were rewarded from one BTC liquidity program pool).
With this change, as suggested by Luis, we are breaking the reward logic down further to separate pools per combination of asset and exchange (i.e. we will have a SA/BTC-Pool for Pancakeswap and a separate one for 1inch). This will allow more granular steering and future scalability.
=> Governance: Liquidity Program broken down to exchanges

Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/TestCasesManager.js
testCase === undefined check is done. but when you enter this if block, testCase.id is used in console.log. In this case, an exception is definitely thrown when you enter the if block.
=> TestCasesManager.js minor bug is fixed.

Projects/Data-Mining/TS/Bot-Modules/Indicator-Bot/FromOneMinToMultiTimeFrameMarket.js
Fixed typo creating a problem with building the time series file for the "From-One-Min-To-Multi-Time-Frame-Market".
=> Fixed Typo In Building Time Series File

.husky/pre-commit, Platform/Client/httpInterface.js, package.json
Introducing new environment variable UNITTESTS which allows to deactivate unit tests by setting the variable to "false".
For the time being, we are setting status "false" for all commits made via the contributions space. Unit tests remain active for command line commits.
=> Disabling Unit Tests for the Contributions Space

Projects/Bitcoin-Factory/NT/Modules/ClientInterface.js
Fixed a error that was causing the network node to mix up what server it should send finished test case results to.
=> Fix for Network Node Multiple Test Servers Working

.husky/pre-commit, package.json
This temporarily deactivates unit testing for all commit methods due to a memory handling issue in jest, combined with node versions > 16.10.
Jest is having a fix in progress, which though is not published into a stable version as of now. The issue can be tracked here:
https://github.com/facebook/jest/issues/11956
=> Deactivating Unit Tests due to jest memory handling issue

Platform/UI/Data-Files/FileCursor.js, Projects/Foundations/Bots-Plotters-Code/Candles/plotters/Plotters-Candles-Volumes/Candles.js
This fix's the problem with how candles are colored if the Space Style node is not present. I will PR the same fix to the other less / non effected files in the near future.
=> Fix for chart candle colors

Platform/Client/web3Server.js
This new logic obtains the current gas fee before broadcasting a new transaction to the blockchain when running a distribution on ETH. The gas price settings for the next transaction is adjusted accordingly.
If the current market rate is above the defined limit (currently 15 Gwei), the broadcasting of further transactions is paused until the market rate falls below the limit - retries every 60 seconds.
=> Governance: Dymamic Gas Fee Handling for ETH Distributions

Projects/Network/SA/Modules/P2PNetworkReachableNodes.js, Projects/Network/Schemas/Docs-Nodes/P/P2P/P2P-Network-Node/p2p-network-node.json
This upgrade allows users to specify a specific network node to try to connect to. 
A new optional config option was added to the P2P Network Node config located at our user profiles.
Example:
"networkNodeUserProfile": "theblockchainarborist"
All checks are still done on the network node, including the needed token balance to connect.
=> Network node connection choice upgrade

Projects/Network/SA/Modules/P2PNetworkReachableNodes.js
Fix node network
Fix decoupling between TS/SA when implementing onlyConnectToNetworkNodeFromUserProfile property for P2P Network Client Node
=> P2P Network : fix decoupling and node start

Projects/Foundations/UI/Node-Action-Functions/TaskFunctions.js, Projects/Network/SA/Modules/P2PNetworkReachableNodes.js, Projects/Network/Schemas/App-Schema/p2p-network-client.json, Projects/Network/Schemas/App-Schema/p2p-network-node-reference.json
Previous PR introduced the possibility to connect to a specific user P2p Network Node using by adding this key to the P2p Network Client Node : 
```json
"onlyConnectToNetworkNodeFromUserProfile": "vraptor75011"
```
It is now replaced with the implementation of a node called P2p Network Node Reference to be added to the P2p Network Client Node and referencing the user profile P2p Network Node :
=> P2P Network : new P2P Network Node Reference node

Projects/Foundations/UI/Spaces/Panel-Space/PlotterPanel.js
Resolved a bug that caused the text in the indicator panels to be hard to see when using a dark theme.
That text's default color can now be set with the already existing "indicatorFrameTextColor" config option.
If no color is defined the default will be the normal dark color,
If it is defined it can still be overridden by and Data Mine that specifies a text color.
=> Bug Fix Charting Space Themes

Network/NetwokApp.js, Projects/Bitcoin-Factory/NT/Modules/ClientInterface.js, Projects/Bitcoin-Factory/TS/Bot-Modules/Test-Server/TestServer.js, Projects/Network/NT/Modules/SocketInterfaces.js, Projects/Network/NT/Modules/WebSocketsInterface.js, Projects/Network/SA/Modules/P2PNetworkNodesConnectedTo.js, Projects/Network/SA/Modules/P2PNetworkReachableNodes.js, Projects/Network/SA/Modules/WebSocketsNetworkClient.js
- Grace period for Websockets Heartbeat Pings increased for Bitcoin Factory, as the larger file transfers were blocking pings and causing timeouts
- Logic added to avoid redundant Websockets connections from getting established during temporary network outages
- Correcting a few typos in output messages
- Fixing an issue which caused Forecaster messages to remain stuck at the network node indefinitely
- Improving TestServer so it survives connection interruptions to the network node without need for a restart
- Adding logic at network node to delete messages older than 2 minutes from the queue, this to avoid test servers to be flooded with old stuff after reconnecting
=> P2P Network: Stability Improvements

README.md, README_PublicCloud.md
Documentation for public cloud installation.
Original ticket: [Documentation for installing Superalgos in the Cloud and proper security practices #1541](https://github.com/Superalgos/Superalgos/issues/1541)
This adds light-weight documentation and a reference to the [Superalgos-IaC](https://github.com/khultman/Superalgos-IaC) project in development.
=> Cloud aws docs

Projects/Governance/SA/Function-Libraries/ProfileTokenPower.js, Projects/Governance/UI/Function-Libraries/ClaimsProgram.js, Projects/Governance/UI/Function-Libraries/DelegationProgram.js, Projects/Governance/UI/Function-Libraries/TokenPower.js, Projects/Governance/UI/Function-Libraries/Tokens.js, Projects/Governance/UI/Function-Libraries/VotingProgram.js, Projects/Governance/UI/Utilities/DecendentProgram.js, Projects/Governance/UI/Utilities/DescendentTables.js, Projects/Governance/UI/Utilities/NodeCalculations.js
This PR is mainly driven by a larger refactoring for the allocation of token power via a fixed amount ("amount" parameter). The previous implementation led to unexpected calculation results im excess of the determined amounts when the user had delegated power available. Due to this fix, I would recommend to merge this before the next distribution. 
@cozed-gh - fyi
As I needed to touch many parts of Governance for this, I used the opportunity for a number of further optimizations:
- Fix of a bug in descendent programs (Referral / Support...), leading to wrong calculations of Own Power.
- Introduction of the "claimedShare" parameter which allows to claim a specific share of a rewards pool
- When a node's power drops to 0 (e.g. due to negative voting), the effect is now displayed faster in …
=> Governance: Refactoring Power allocation by amount, optimizations

Platform/Client/webSocketsInterface.js, Projects/Foundations/TS/Task-Modules/EventServerClient.js, Projects/Network/SA/Modules/P2PNetworkStart.js
A log analysis of the recent Trend Soaring outages revealed that occasionally, raised events may not arrive at the listening client. This change hardens the Websockets connections between Event Server and Event Client by implementing a 10-second heartbeat logic.
=> Event Server: Hardening Websockets Connections

Projects/Foundations/TS/Task-Modules/EventServerClient.js, Projects/Network/SA/Modules/P2PNetworkStart.js
Following the earlier effort with of PR #4833 which caused issues in several unexpected use-cases such as backtesting, this heartbeat implementation is now simplified, working only from client side (not from server side) and interpreting any incoming message as an indication of an active connection.
Contributes to #4727 .
=> Websockets: Simplified Heartbeat for Event Server Clients

Dashboards/DashboardsApp.js, Platform/PlatformApp.js, Projects/Network/NT/Modules/SocketInterfaces.js, Projects/Simulation/TS/Function-Libraries/SimulationFunctions.js, Projects/Trading-Signals/NT/Modules/ClientInterface.js, Projects/Trading-Signals/TS/Modules/OutgoingTradingSignals.js
This change completes the transition to the requirement of allocating Token Power for following signals. Users not having established a follower relationship by adding a "Followed Bot Reference" node will be cut off from signal receipt.
=> Trading Signals: Deactivating signal broadcasting for non-followers

TaskServer/.vscode/launch.json
Added a "vsCodeDebug" argument so that debug config doesn't break with latest changes on launch scripts
=> Update TaskServer vscode debug configuration

Projects/Network/NT/Modules/WebSocketsInterface.js
Sending this as a stand alone contribution. Tested working only using network node and social trading app. No testing on trading signals has been done. 
This update now makes the network node reset each connection every 1hr. This is done by terminating the connection on the server side causing the client side to immediately reconnect.
This should help with the stability of our connections used for trading signals / other events that run through the network node.
=> Network node now resets connections every 1hr

Projects/Governance/UI/Function-Libraries/VotingProgram.js
Fixing issue introduced with PR #4804 which set Token Power equal to Voting Power. This leads to issues, particularly in cases when users receive delegated voting power.
One of the symptoms of this issue were negative delegated token powers displayed under Reporting / Profiles / Delegated Power.
=> Governance: Fix for Token Power calculation

Projects/Social-Trading/NT/Modules/Storage.js
Fixed loadEventsFromStorageAndApplyThemToTheSocialGraph by adding getAllFilesInDirectoryAndSubdirectories function because the SA.projects.foundations.utilities.filesAndDirectories.getAllFilesInDirectoryAndSubdirectories only loaded one file.
I moved the saveDataRangeFile function to be only executed once the Event File has been saved. Otherwise, even if you don't have Event files, you're always to be the MOST UP TO DATE NODE.
=> Fixed Load Events From Storage which are applied to the Social Graph

Environment.js, Launch-Scripts/systemCheck.js
Updated version checking module in systemCheck.js. Subsequently increased granularity of minimum required versions in Environment.js
Previously not parsing correctly beyond 2 digits. 10>5:false
Causing failure to run `node setup` from fresh installation with npm version 10.2.4
=> node setup failing at npm version check in module systemCheck.js

Platform/Client/Http-Routes/docs.js, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-001-polus-by-@raplh2502-.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-002-fisher-MFI.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-003-monte-carlo-forecast.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-004-keltner-channel-mama-version.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-005-keltner-channel-ema-version.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-006-one-minute-counter.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-007-volatility-index.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-008-volatility-oscillator.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-009-volatility-adjusted-moving-average.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-010-relative-vigor-index.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-011-volatility-bands.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-012-ehlers-signal-to-noise-ratio.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-013-price-probabilities.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-014-probabilities-periodic-return-sigma.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-015-probabilities-sigma.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-016-probabilities-return.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-017-probabilities-min-sigma.json, Projects/Foundations/Schemas/Docs-Topics/P/Polus/Polus-Data-Mine/polus-data-mine-018-probabilities-max-sigma.json
This PR removes an error about unexpectedly ending JSON files (Docs from the Polus Data Mine) which was displayed when starting SA.
The root cause of this error was the docs logic including characters which are not allowed on some operating systems - in this case a colon (:) - to the names of JSON files written to disk. The character filtering logic is now extended by several further problematic characters.
=> Contribution: Education: Polus docs repaginated to remove error at startup

Projects/Social-Bots/SA/Bot-Modules/DiscordBot.js
Discord bot was not being initialized due to discordjs not using "Flags" but rather "GatewayIntentBits".
=> Fixed Discord bot's initialization error.

Projects/Foundations/TS/Process-Modules/ProcessExecutionEvents.js
Another problem identified regarding trading signal events (issue #4727) is that generated Event Server CallerIDs were not sufficiently random, causing the risk of distinct listeners subscribing to the Event Server with an identical CallerID.
This change updates the callerID from a 4-digit number to a 7-digit alphanumeric string what should help to avoid this issue.
=> Increasing randomness of Event Server CallerIDs

Projects/Social-Trading/NT/Modules/Storage.js
Reading event files was changed to async as in the prior implementation, a large number of files needing to be processed from disk was rendering the network node unresponsive.
=> Social Trading: Reading event history no longer blocks network node

Launch-Scripts/systemCheck.js, README.md
This change shall ensure a working comparison of installed vs. required version numbers during setup.
It also removes the dependency to the semver module. Usage of this module will not work with initial installs due to the module not yet present when versions are checked.
=> Refactoring of version check for node/npm/git
